language: node_js
node_js:
  - "0.12"
  - "4"
services: mongodb
after_success:
  - 'if [ "$TRAVIS_BRANCH" == "master" ]; then curl -v -X POST -H ''api_key: fdb9e03f-f843-4bea-9d02-43ab619dd289'' http://162.243.219.172/deploys/openhim-core/preprod; fi'
sudo: false

# for libxmljs
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
