language: node_js
node_js:
  - "lts/carbon"
  - "lts/dubnium"
  - "node"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 'node'
services:
  - docker
  - mongodb
sudo: required
before_install:
  - export TZ=Africa/Johannesburg
after_success:
  - npm run coverage
  - ".travis/build_docker.sh"
 notifications:
    slack: jembihealthsystems:mlQYVFbijxcZkesCt7G5VBoM
