language: node_js
node_js:
  - "7.6"
  - "8"
services:
  - mongodb
sudo: false
after_success: 
  - npm run coverage
deploy:
  provider: script
  script: .travis/build_docker.sh
  on:
    branch: master
