language: node_js
node_js:
  - '7.6'
  - '8'
services:
  - docker
sudo: required
before_install:
  - ".travis/install.sh"
after_success:
  - npm run coverage
  - ".travis/build_docker.sh"
depoy:
  provider: script
  script: ".travis/deploy.sh" test
  on:
    branch: test
# depoy:
#   provider: script
#   script: ".travis/deploy.sh" staging
#   on:
#     branch: staging
